#1.????
#1.0??????
spring:
  profiles:
    active: dev
#1.1????

#2.????
#2.1  ????
---
spring:
  config:
    activate:
      on-profile: pro
server:
  port: 80
#2.2  ????
---
spring:
  config:
    activate:
      on-profile: dev
server:
  port: 81
#2.3  ????
---
spring:
  config:
    activate:
      on-profile: test
server:
  port: 82