spring:
  mail:
    #host:????????SMTP?????:POP3/IMAP  ??????????????????
    host: smtp.qq.com
    #username????QQ??
    username: 1693905917@qq.com
    #????????????????????????
    password: scojadxuvjmodeeh
