#????Client???????
server:
  port: 80
#?????Client??????Admin???????????Admin?????
spring:
  boot:
    admin:
      client:
        #???????http://
        url: http://localhost:8080
management:
  #????Client??????????
  endpoint:
    health:
      #???never
      show-details: always
  #???????Client??????????
  endpoints:
    web:
      exposure:
        #?* ????Client????????????  *???""???''??
        include: "*"